### ISSUE TITLE
What's the graphProcessedData mean?

### ISSUE THREAD

**Issue by HamsterCoderSim** [kdotdot/gnn-deap-eeg#1]
Hello,kdotdot
There is  code `PROCESSED_DIR = 'data/graphProcessedData'` in DEAPDataset.py file  , I want to know what the graphProcessedData mean? I have got the DEAP dataset, and shat I should do to get the `graphProcessedData`.

**Comment by kdotdot** [comment]
Hello codeDaoZhang,

**Comment by kdotdot** [comment]
Hello codeDaoZhang,
The DEAPDataset.py file is a Pytorch Geometric Inmemory Dataset implementation of the DEAP dataset. 
If you want to make it run you have to instantiate the object like so:

`dataset = DEAPDataset(root= ROOT_DIR, raw_dir= RAW_DIR, processed_dir=PROCESSED_DIR,args=args,expand_3d=False)`

Running that line will generate the processed graphs inside the directory you specify under PROCESSED_DIR if they are not available. If they are available it will just read the processed graphs and return them to you.

Initialization requires a set of arguments. If you just want to test it you can create an args object that you pass onto the dataset liek so:

```
ROOT_DIR = './'
RAW_DIR = 'data/matlabPREPROCESSED'
PROCESSED_DIR = 'data/graphProcessedData'

class args: 
    def __init__(self):
        self.participant_from = 1
        self.participant_to = 1
        self.classification_labels = False
        self.global_connections = False
        

args = args()

dataset = DEAPDataset(root= ROOT_DIR, raw_dir= RAW_DIR, processed_dir=PROCESSED_DIR,args=args,expand_3d=False)
```

That should generate the Pytorch Geometric graphs under PROCESSED_DIR

**Comment by HamsterCoderSim** [comment]
Bro, thank u for reply. It gives me a lot of help
