### ISSUE TITLE
Some questions about the dataset

### ISSUE THREAD

**Issue by HamsterCoderSim** [kdotdot/gnn-deap-eeg#2]
Hello kdotdot,
Today I have debug your code, and I've encountered some problems. Specifically, it can be described as follows:
## The training methods
   1. As usual, the original shape of EEG data is `trails x electrodes x dataLen`. And I usually  transpose the EEG data to `trails x dataLen x electrodes`.And then the num of graph is `trails x dataLen` , the `num_node_features` of every graph is 1. 
   2. Now, I see that you takes the data(`electrodes x dataLen`) of per trail as a graph, so that the `num_node_features` of every graph is `dataLen`.
I want to make it clear that which method the result of papers belongs to ? 

## The code annotation
   In DEAPDataset.py, there's a line that says **# 1 graph per window (12 per video with window size 672)**. Does it point the training method 1?

**Comment by kdotdot** [comment]
Hello again codeDaoZhang,

I am not sure I understand what you mean. As far as I know num_node_features should equal dataLen. If your question is what training method I am using I'd say number 2. Each node feature vector is not a 1 element vector but a dataLen vector instead.

Regarding the code annotation I am taking windows from the input data. If the size of each window is 672 then I will have 12 windows ( dataLen/672 = 12). Windows are taken to try and extract temporal dependencies.

**Comment by HamsterCoderSim** [comment]
Thank you for your help, best wishes to you. 😄
